export const FILTER_BY_PLATFORM = 'FILTER_BY_PLATFORM';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_SORT = 'FILTER_BY_SORT';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
